# 保存截图文件所在的文件夹
# 确保截图名称仅为数字，从 1 开始，如 1.png,2.png，方便确认顺序
ImageDirectory = ""

# 横向裁剪的比例，默认为 0
# 如果不为 0，则会在水平方向从两端压缩
VerticalRate = 0

# 纵向裁剪的比例，即字幕占整体截图的比例
# 请选择 1-9 之间的数字，默认为 2，会按 2/10 的比例从
# 截图中截取字幕
HorizontolRate = 2

# 请选择输出的图片名称
# 目前为简化只支持 jpg/jpeg 格式，后续会增加 png/gif 格式
OutputFilename = "output.JPG"